export const CATEGORY_1 = "Concert tickets"
export const CATEGORY_2 = "Workshops"
export const CATEGORY_1_SINGULAR = "Concert ticket"
export const CATEGORY_2_SINGULAR = "Workshop"
export const MAX_CATEGORY_DISPLAY = 30
export const NUM_CUSTOM_OPTIONS = 5 //number of custom options the participent can add to each category
export const MIN_RATING = 1
export const MAX_RATING = 1000
export const RATING_MARGIN = 200 // how close do we want the rating of the new options to be to the min/max values
export const MINIMAL_TIME = 1 //in seconds
export const N_MATCHES = 10
export const N_SETS = 3
export const ATTENTION_TRIALS = 10 //presentage of trials to be attention trails
